#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  OneID — Autostart Setup  (run ONCE on the RPi desktop terminal)
#  Usage:  ./setup-autostart.sh [MACBOOK_IP]
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MACBOOK_IP="${1:-192.168.1.100}"

echo ""
echo "  ╔══════════════════════════════════════════════════════╗"
echo "  ║   OneID  ·  Autostart Setup  (Raspberry Pi 4)       ║"
echo "  ╚══════════════════════════════════════════════════════╝"
echo "  MacBook IP → ${MACBOOK_IP}"
echo ""

# ── 1. Install deps ───────────────────────────────────────────────────────────
for pkg in firefox-esr unclutter curl; do
  if ! command -v "$pkg" &>/dev/null; then
    echo "  [deps] Installing ${pkg}..."
    sudo apt-get install -y "$pkg"
  fi
done

# ── 2. Find npm / node full path ──────────────────────────────────────────────
# LXDE autostart uses a minimal PATH — we must hardcode the npm binary path.
NPM_BIN="$(command -v npm 2>/dev/null)"
if [ -z "$NPM_BIN" ]; then
  # Try common nvm / system locations
  for candidate in \
    "$HOME/.nvm/versions/node/$(ls $HOME/.nvm/versions/node 2>/dev/null | sort -V | tail -1)/bin/npm" \
    "/usr/local/bin/npm" \
    "/usr/bin/npm"; do
    if [ -f "$candidate" ]; then NPM_BIN="$candidate"; break; fi
  done
fi

echo "  [npm]  Found at: ${NPM_BIN:-NOT FOUND}"
[ -z "$NPM_BIN" ] && echo "  [error] npm not found! Install Node.js first." && exit 1

NODE_BIN="$(dirname "$NPM_BIN")/node"
echo "  [node] Found at: ${NODE_BIN}"

# ── 3. Write the kiosk launcher wrapper ──────────────────────────────────────
# This wrapper sources PATH correctly and is what autostart actually calls.
WRAPPER="$SCRIPT_DIR/kiosk-autostart-wrapper.sh"
cat > "$WRAPPER" << WRAPPER_SCRIPT
#!/usr/bin/env bash
# Auto-generated by setup-autostart.sh — do not edit manually

# Source user environment so npm/node are available
export HOME="${HOME}"
export PATH="${PATH}:$(dirname "$NPM_BIN")"
export VITE_FACE_API_URL="http://${MACBOOK_IP}:8000"

# Log output for debugging
LOG="/tmp/oneid-kiosk.log"
exec > "\$LOG" 2>&1

echo "[wrapper] Starting OneID kiosk at \$(date)"
echo "[wrapper] PATH=\$PATH"
echo "[wrapper] NPM=$(command -v npm)"
echo "[wrapper] NODE=$(command -v node)"

cd "$SCRIPT_DIR"
bash "$SCRIPT_DIR/run-kiosk.sh" "${MACBOOK_IP}"
WRAPPER_SCRIPT
chmod +x "$WRAPPER"
echo "  [wrap]  Written: ${WRAPPER}"

# ── 4. Install XDG autostart .desktop file ───────────────────────────────────
# .desktop files in ~/.config/autostart/ are the most universally supported
# method — works with LXDE, PIXEL, openbox, and most RPi desktop environments.
AUTOSTART_DESKTOP_DIR="$HOME/.config/autostart"
mkdir -p "$AUTOSTART_DESKTOP_DIR"

cat > "$AUTOSTART_DESKTOP_DIR/oneid-kiosk.desktop" << DESKTOP_FILE
[Desktop Entry]
Type=Application
Name=OneID Kiosk
Comment=OneID Aadhaar Verification Kiosk
Exec=lxterminal --title="OneID Kiosk" -e bash $WRAPPER
Terminal=false
Hidden=false
X-GNOME-Autostart-enabled=true
DESKTOP_FILE

echo "  [xdg]   Written: ${AUTOSTART_DESKTOP_DIR}/oneid-kiosk.desktop"

# ── 5. Also update LXDE autostart as fallback ─────────────────────────────────
LXDE_AUTOSTART="$HOME/.config/lxsession/LXDE-pi/autostart"
mkdir -p "$(dirname "$LXDE_AUTOSTART")"
# Remove all old OneID/chromium kiosk entries
grep -v -E "(run-kiosk|kiosk-autostart|chromium.*8080|oneid)" "$LXDE_AUTOSTART" > /tmp/_lxde_tmp 2>/dev/null || true
mv /tmp/_lxde_tmp "$LXDE_AUTOSTART" 2>/dev/null || true
echo "@lxterminal --title=OneID-Kiosk -e bash $WRAPPER" >> "$LXDE_AUTOSTART"
echo "  [lxde]  Written: ${LXDE_AUTOSTART}"

# ── 6. Auto-login to desktop (no password prompt on boot) ─────────────────────
sudo raspi-config nonint do_boot_behaviour B4 2>/dev/null && echo "  [boot]  Auto-login to desktop enabled ✓" || true

echo ""
echo "  ──────────────────────────────────────────────────────"
echo "  ✓  Setup complete!"
echo ""
echo "  On next boot:"
echo "    • Desktop loads automatically (no password)"  
echo "    • A terminal window opens showing kiosk status"
echo "    • Firefox opens fullscreen at /kiosk"
echo ""
echo "  To debug if it fails, check: cat /tmp/oneid-kiosk.log"
echo ""
echo "  Now run:  sudo reboot"
echo "  ──────────────────────────────────────────────────────"
echo ""
