/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as OfficialRouteImport } from './routes/official'
import { Route as SuperRouteImport } from './routes/super'
import { Route as UserRouteImport } from './routes/user'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialRoute = OfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consumer': typeof ConsumerRoute
  '/kiosk': typeof KioskRoute
  '/official': typeof OfficialRoute
  '/super': typeof SuperRoute
  '/user': typeof UserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consumer': typeof ConsumerRoute
  '/kiosk': typeof KioskRoute
  '/official': typeof OfficialRoute
  '/super': typeof SuperRoute
  '/user': typeof UserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consumer': typeof ConsumerRoute
  '/kiosk': typeof KioskRoute
  '/official': typeof OfficialRoute
  '/super': typeof SuperRoute
  '/user': typeof UserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consumer' | '/kiosk' | '/official' | '/super' | '/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consumer' | '/kiosk' | '/official' | '/super' | '/user'
  id:
    '__root__' | '/' | '/consumer' | '/kiosk' | '/official' | '/super' | '/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsumerRoute: typeof ConsumerRoute
  KioskRoute: typeof KioskRoute
  OfficialRoute: typeof OfficialRoute
  SuperRoute: typeof SuperRoute
  UserRoute: typeof UserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official': {
      id: '/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof OfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsumerRoute: ConsumerRoute,
  KioskRoute: KioskRoute,
  OfficialRoute: OfficialRoute,
  SuperRoute: SuperRoute,
  UserRoute: UserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
